import { ILogTarget } from "./ILogTarget";
/**
 * A virtual representation of a discrete value logged to from AssemblyScript.
 */
export declare class LogValue {
    /**
     * If a pointer is referenced, this is the precise memory location of the referenced block of
     * data.
     */
    pointer: number;
    /**
     * If a pointer is referenced and isn't a string, this is the size of the referenced block of
     * data.
     */
    offset: number;
    /**
     * If a pointer is referenced and ins't a string, this is an array of bytes to be logged byt the
     * logger.
     */
    bytes: number[];
    /**
     * If an array is referenced, it's values will be here.
     */
    values: number[];
    /**
     * This is a message generated by the TestSuite to be displayed in the logger.
     */
    message: string;
    /**
     * This is the relevant stack trace, filtered with the `/wasm/i` regex.
     */
    stack: string;
    /**
     * This is the referenced log target.
     */
    target: ILogTarget | null;
    /**
     * This is the raw logged value.
     */
    value: number | null;
    /**
     * This is a function pointer is an index.
     */
    fnPointer: number;
}
