module.exports = {
  "mode": "modules",
  "out": "docs",
  exclude: [
    "**/assembly/assembly/**/*.ts",
    "**/core/assembly/**",
    "**/__tests__/**",
    "**/node_modules/**",
    "**/*.spec.ts",
    "**/*.amd.d.ts",
    "**/*.portable.d.ts",
    "**/@types/jest/**",
    "**/lib/**",
    "**/assembly/types/env.d.ts",
  ],
  name: "as-pect",
  includeDeclarations: true,
  excludePrivate: true,
  excludeProtected: true,
  excludeExternals: true,
  skipInternal: true,
};