import { ILogTarget } from "./ILogTarget";

/**
 * A virtual representation of a discrete value logged to from AssemblyScript.
 */
export class LogValue {
  /**
   * If a pointer is referenced, this is the precise memory location of the referenced block of
   * data.
   */
  public pointer: number = 0;

  /**
   * If a pointer is referenced and isn't a string, this is the size of the referenced block of
   * data.
   */
  public offset: number = 0;

  /**
   * If a pointer is referenced and ins't a string, this is an array of bytes to be logged byt the
   * logger.
   */
  public bytes: number[] = [];

  /**
   * This is a message generated by the TestSuite to be displayed in the logger.
   */
  public message: string = "";

  /**
   * This is the relevant stack trace, filtered with the `/wasm/i` regex.
   */
  public stack: string = "";

  /**
   * This is the referenced log target.
   */
  public target: ILogTarget | null = null;
}
