import { TestResult } from "../test/TestResult";
import { TestGroup } from "../test/TestGroup";
/**
 * A virtual representation of a discrete value logged to from AssemblyScript.
 */
export declare class LogValue {
    /**
     * If a pointer is referenced, this is the precise memory location of the referenced block of
     * data.
     */
    pointer: number;
    /**
     * If a pointer is referenced and isn't a string, this is the size of the referenced block of
     * data.
     */
    offset: number;
    /**
     * If a pointer is referenced and ins't a string, this is an array of bytes to be logged byt the
     * logger.
     */
    bytes: number[];
    /**
     * This is a message generated by the TestSuite to be displayed in the logger.
     */
    message: string;
    /**
     * This is the relevant stack trace, filtered with the `/wasm/i` regex.
     */
    stack: string;
    /**
     * This is the referenced test, if it was generated during a test.
     */
    test: TestResult | null;
    /**
     * This is the referenced group, if it was generated during a describe group.
     */
    group: TestGroup | null;
}
//# sourceMappingURL=LogValue.d.ts.map