name: Test
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check syntax
    strategy:
      matrix:
        node_version: ["15"]
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: npm install
    - name: Check sources
      run: npm run check
  test-latest:
    name: "${{ matrix.os }}, node ${{ matrix.node_version }}"
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: ["current"]
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: "current"
    - name: Install dependencies
      run: npm install
    - name: Test sources
      run: npm run test:ci
    - name: print coverage data
      run: cat ./packages/core/coverage/lcov.info
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./packages/core/coverage/lcov.info
  test-lts:
    name: "${{ matrix.os }}, node ${{ matrix.node_version }}"
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: ["lts_latest"]
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: "lts_latest"
    - name: Install dependencies
      run: npm install
    - name: Test sources
      run: npm run test:lts:ci
    - name: print coverage data
      run: cat ./packages/core/coverage/lcov.info
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./packages/core/coverage/lcov.info
