name: Test
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check syntax
    strategy:
      matrix:
        node_version: ["18"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: npm install
    - name: Check sources
      run: npm run check
  test:
    name: "${{ matrix.os }}, node ${{ matrix.node_version }}"
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: ["16", "18", "19"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: npm install
    - name: Test sources
      run: npm run test:ci
    - name: print coverage data
      run: echo 'repo_token:' ${{ secrets.COVERALLS_GITHUB_TOKEN }} > ./.coveralls.yml | cat ./packages/core/coverage/lcov.info
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./packages/core/coverage/lcov.info
